AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/.simplecov'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'vendor/**/*'
    - 'plugins/**/*'
    - 'test/*'
    - 'Gemfile'
  DisplayCopNames: true

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 5

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 3
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 5

Rails:
  Enabled: true

Rails/ActionFilter:
  EnforcedStyle: action

Rails/TimeZone:
  EnforcedStyle: strict

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AndOr:
  EnforcedStyle: always

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
